### PR TITLE
Using go install to expedite usage

### PR DESCRIPTION
**Pull request by nikolaydubina**
This actually works! much more convenient!

image

> licence line is not changed. just whitespace. I guess you are using windows.

### CODE REVIEW

**Comment by nikolaydubina** [comment]
also. recommend more specific names for this tool. reserving word "description" and "review" for entire OS is a bit too much!

**Comment by nikolaydubina** [comment]
cc: @ravilushqa

**Comment by nikolaydubina** [comment]
also. I added this tool to go-recipes ! feel free to make PR if you want to change ! :)

http://github.com/nikolaydubina/go-recipes

**Comment by ravilushqa** [comment]
@nikolaydubina thanks for contribution!

**Comment by ravilushqa** [comment]
> also. recommend more specific names for this tool. reserving word "description" and "review" for entire OS is a bit too much!
> 
> maybe `gh-auto-description` and `gh-auto-review`.
> 
> or even single tool with options?
> 
> `gitgpt description` + `gitgpt review`?

Sounds great! I'll consider it.

**Pull request merged**
